# -*- coding: utf-8 -*-
"""Phthon.assognment.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTA2coaIQ44NTsEjfyHpt_O6jZ_1-dHL
"""

# Q1.1 - Variables & Dynamic Typing

age = 25

print(age)
print(type(age))

# Q1.2 - Dynamic Typing

num = "10"

print(num)
print(type(num))

num = 10

print(num)
print(type(num))

# Q1.3 - Python vs C/Java

# Answer:
# C/Java me variable ka type pehle declare hota hai,
# jabki Python dynamically typed language hai.

# Q1.4 - Predict the Output

x = 5
x = "five"

print(x)

# Q2.1 - Create variables of int, float, string, bool and list

a = 10
b = 10.5
c = "Hello"
d = True
e = [1, 2, 3]

print(a, type(a))
print(b, type(b))
print(c, type(c))
print(d, type(d))
print(e, type(e))

# Q2.2 - Difference between List and Tuple

my_list = [1, 2, 3]
my_tuple = (1, 2, 3)

# List can be changed
my_list[0] = 100

print(my_list)
print(my_tuple)

# Q2.3 - Check if Item is Available

price = 499.99
in_stock = True

if in_stock:
    print("Available")

# Q3.1 - Difference between is and ==

# == checks whether the values are equal.
# is checks whether both variables refer to the same object.

# Q3.2 - Compare Two Lists using == and is

a = [1, 2, 3]
b = [1, 2, 3]

print(a == b)
print(a is b)

# Q3.3 - Compare Integer Objects

x = 100
y = 100

print(x is y)
print(x == y)

p = 1000
q = 1000

print(p is q)
print(p == q)

# Q3.4 - Check Types of Different Objects

print(type(5))
print(type("hi"))
print(type([1, 2]))

# Q4.1 - Use upper(), lower() and title()

name = "pYTHOn"

print(name.upper())
print(name.lower())
print(name.title())

# Q4.2 - Predict the Output

s = "Hello"

s.lower()

print(s)

# Q4.3 - Use lower() and Reassign the Value

s = "Hello"

s = s.lower()

print(s)

# Q4.4 - Strip, Count and Split a String

sentence = " Learning Python is fun "

# Remove leading and trailing spaces
clean_sentence = sentence.strip()

# Count the letter 'n'
count_n = clean_sentence.count("n")

# Split the sentence into words
words = clean_sentence.split()

print(clean_sentence)
print(count_n)
print(words)

# Q5.1 - Print numbers 1 through 10

for i in range(1, 11):
    print(i)

# Q5.2 - Print every 3rd number from 0 to 30

for i in range(0, 31, 3):
    print(i)

# Q5.3 - Predict the output

for i in range(10, 0, -2):
    print(i)

# Q5.4 - Rewrite for loop as while loop

i = 0

while i < 20:
    print(i)
    i += 4

# Q5.5 - Count how many times i < 10 is evaluated

i = 0

while i < 10:
    print(i)
    i += 1

# Q6.1 - Print even numbers from 1 to 20

for i in range(1, 21):
    if i % 2 == 0:
        print(i)

# Q6.2 - FizzBuzz from 1 to 15

for i in range(1, 16):

    if i % 15 == 0:
        print("FizzBuzz")

    elif i % 3 == 0:
        print("Fizz")

    elif i % 5 == 0:
        print("Buzz")

    else:
        print(i)

# Q6.3 - Predict the output

for i in range(0, 5):

    if i % 3 == 0:
        print(i)

    elif i % 3 == 1:
        print(i + 10)

    else:
        print(i - 10)

# Q6.4 - Check whether a number is positive, negative or zero

number = int(input("Enter a number: "))

if number > 0:
    print("Positive")

elif number < 0:
    print("Negative")

else:
    print("Zero")

# Q7.1 - Create my_abs() function

def my_abs(val):

    if val < 0:
        return 0 - val

    return val


print(my_abs(5))
print(my_abs(-7))
print(my_abs(0))

def my_abs(val):
    if isinstance(val, str):
        return "Invalid input: string cannot be compared"

    if val < 0:
        return 0 - val
    return val

print(my_abs("Hi"))

# Q7.3 - Function prints absolute value instead of returning it

def print_abs(val):

    if val < 0:
        print(0 - val)
    else:
        print(val)


x = print_abs(-2.7)

print(x)

# Q7.4 - Reassigning a local variable inside a function

def inc_val(val):
    val = val + 1


x = 7

inc_val(x)

print(x)

# Q7.5 - Swap two local variables inside a function

def swap_message(val1, val2):

    val1, val2 = val2, val1

    print("Inside function:")
    print(val1)
    print(val2)


x = 6
y = 3

swap_message(x, y)

print("Outside function:")
print(x)
print(y)

import inspect
# Q8.1 - Predict the output and explain the error

def my_abs(val):
    if val < 0:
        return 0 - val
    return val

# The error occurs because 'val' is a local variable within the function 'my_abs'
# and is not defined in the global scope where print(val) is called.
# To fix this, we need to call the function with an argument.

print(my_abs(-5)) # Example of correct usage

# Q8.3 - Trying to modify a global variable without the global keyword

counter = 0

def increment_counter():
    global counter
    counter = counter + 1

increment_counter()
print(counter)

# Q8.4 - Correctly modifying a global variable using the global keyword

counter = 0

def increment_counter():
    global counter
    counter = counter + 1

increment_counter()
print(counter)

# Q1 - Shopping Cart Item

item_name = "Notebook"
print(item_name)
print(type(item_name))

item_name = 101
print(item_name)
print(type(item_name))

# Q2 - Student ID Card

name = "Ananya"
roll_number = 21
height_in_cm = 152.5
is_hostel_student = True

print(f"Name: {name}")
print(f"Roll Number: {roll_number}")
print(f"Height: {height_in_cm}")
print(f"Hostel Student: {is_hostel_student}")

# Q3 - Comparing Two Friends' Ages

sam_age = 20
priya_age = 20

print(sam_age == priya_age)
print(sam_age is priya_age)

# Q4 - Fixing a Messy Name

raw_name = " rohan MEHTA "
cleaned_name = raw_name.strip().title()
print(cleaned_name)

# Q5 - Watering Plants Reminder

for i in range(1, 8):
    print(f"Day {i}: Watered the plant")

# Q6 - Counting Down for a Rocket Launch

i = 5
while i >= 1:
    print(i)
    i -= 1
print("Blast off!")

# Q7 - Movie Ticket Price

age = 10

if age < 12:
    print("Ticket price: ₹100")
else:
    print("Ticket price: ₹250")

# Q9 - Simple Greeting Function

def greet_student(name):
    print(f"Hello, {name}! Welcome to Python class.")

greet_student("Meera")
greet_student("Karan")

# Q10 - Add Two Numbers

def add_numbers(a, b):
    return a + b

result = add_numbers(4, 7)
print(result)

# Q11 - Class Attendance Counter

total_students = 0

def mark_present():
    global total_students
    total_students += 1

mark_present()
mark_present()
mark_present()

print(total_students)